Add action
f3d-app/lfs-data-cache-action pull request #3
Opened 2024-09-04 19:40 UTC by mwestphal

2024-09-04 20:28 UTC, Meakk requested changes

2024-09-04 20:28 UTC, Meakk commented on .github/workflows/check_size.cmake
> +  message(FATAL_ERROR "File is is small than 500 bytes, lfs data not correctly recovered")
```suggestion
  message(FATAL_ERROR "File is smaller than 500 bytes, lfs data not correctly recovered")
```

2024-09-05 05:27 UTC, Meakk approved these changes

2024-09-05 05:27 UTC, mwestphal commented on README.md
> +        lfs: false
not needed

2024-09-05 05:28 UTC, mwestphal commented on README.md
> +      uses: f3d-app/lfs-data-cache-action:v1
missing an id

2024-09-05 06:03 UTC, merged